- name: remove network manager
  when: network_systemd_remove_network_manager
  block:

    - name: disable service NetworkManager
      service:
        name: NetworkManager
        enabled: no
      ignore_errors: True  # noqa ignore-errors
      failed_when: False

    - name: remove package network-manager
      package:
        pkg: network-manager
        state: absent
      ignore_errors: True  # noqa ignore-errors
      failed_when: False

- name: remove netplan
  when: network_systemd_remove_netplan
  block:

    - name: remove packages for netplan
      package:
        pkg: ['netplan.io', 'libnetplan0']
        state: absent

    - name: remove /etc/netplan
      file:
        path: /etc/netplan
        state: absent

- name: remove packages for dhcpcd
  package:
    pkg: dhcpcd5
    state: absent
  ignore_errors: True  # noqa ignore-errors
  failed_when: False
  when: network_systemd_remove_dhcpcd

- name: remove networkd-dispatcher
  package:
    pkg: networkd-dispatcher
    state: absent
  ignore_errors: True  # noqa ignore-errors
  failed_when: False
  when: network_systemd_remove_networkd_dispatcher

- name: remove /etc/systemd/network/99-default.link
  file:
    path: /etc/systemd/network/99-default.link
    state: absent

- name: detect files to wipe
  find:
    paths: /etc/systemd/network
    patterns: '*.net*'
  register: network_systemd_files_to_wipe
  when: network_systemd_wipe

- name: wipe files
  file:
    path: '{{ item.path }}'
    state: absent
  loop: '{{ network_systemd_files_to_wipe.files }}'
  when: network_systemd_wipe

- name: deploy networks
  template:
    src: systemd.j2
    dest: '/etc/systemd/network/{{ item.name }}.network'
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  vars:
    sections: '{{ item.sections }}'
  notify: restart systemd-networkd
  loop: "{{ network_systemd_network | rejectattr('name', 'equalto', '') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: deploy netdevs
  template:
    src: systemd.j2
    dest: '/etc/systemd/network/{{ item.name }}.netdev'
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  vars:
    sections: '{{ item.sections }}'
  notify: restart systemd-networkd
  loop: "{{ network_systemd_netdev | rejectattr('name', 'equalto', '') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: deploy links
  template:
    src: systemd.j2
    dest: '/etc/systemd/network/{{ item.name }}.link'
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  vars:
    sections: '{{ item.sections }}'
  notify: update initramfs
  loop: "{{ network_systemd_link | rejectattr('name', 'equalto', '') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: enable and start systemd-networkd
  systemd:
    name: systemd-networkd
    enabled: yes
    state: started
    daemon_reload: yes

- name: create directory /etc/systemd/resolved.conf.d
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: deploy /etc/systemd/resolved.conf.d/resolved.conf
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf.d/resolved.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-resolved

- name: install systemd-resolved
  package:
    name: systemd-resolved
    state: present
  when: ansible_facts.distribution_release not in ['bullseye']

- name: install libnss-resolve
  package:
    name: libnss-resolve
    state: "{{ network_systemd_resolved_libnss | ternary('present', 'absent') }}"

- name: create systemd-resolved.service.d
  file:
    path: /etc/systemd/system/systemd-resolved.service.d
    state: "{{ network_systemd_resolved_debug | ternary('directory', 'absent') }}"  # noqa args[module]
    owner: root
    group: root
    mode: '0755'
  notify: restart systemd-resolved

- name: override systemd-resolved.service
  template:
    src: systemd-resolved.override.conf.j2
    dest: /etc/systemd/system/systemd-resolved.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-resolved
  when: network_systemd_resolved_debug

- name: enable and start systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: yes
    state: started
    daemon_reload: yes

- name: use systemd resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  when: not network_systemd_resolved_stub

- name: use systemd stub-resolv.conf
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  when: network_systemd_resolved_stub

- name: disable networking
  service:
    name: networking
    enabled: no
  ignore_errors: True  # noqa ignore-errors
  failed_when: False
  when: network_systemd_unit_networking_disable

- name: make sure /etc/network exists
  file:
    path: /etc/network
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: network_systemd_etc_network_interfaces_truncate

- name: truncate /etc/network/interfaces
  copy:
    content: ''
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  register: network_systemd_etc_network_interfaces_truncate_result
  when: network_systemd_etc_network_interfaces_truncate

- name: remove /etc/network/interfaces.d
  file:
    path: /etc/network/interfaces.d
    state: absent
  when: network_systemd_etc_network_interfaces_d_remove

#- name: kill dhclient
#  shell: 'if [ "$(pidof dhclient)" ]; then kill "$(pidof dhclient)"; fi'
#  changed_when: False
#  when: network_systemd_unit_networking_disable and network_systemd_etc_network_interfaces_truncate and network_systemd_etc_network_interfaces_truncate_result.changed

- name: create systemd-networkd-wait-online.service.d directory
  file:
    path: /etc/systemd/system/systemd-networkd-wait-online.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: _network_systemd_networkd_wait_online_service_override

- name: deploy systemd-networkd-wait-online.service override
  template:
    src: systemd-networkd-wait-online.service.j2
    dest: /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd
  when: _network_systemd_networkd_wait_online_service_override

- name: "{{ network_systemd_networkd_wait_online | ternary('enable', 'disable') }} systemd-networkd-wait-online.service"
  systemd:
    name: systemd-networkd-wait-online
    enabled: '{{ network_systemd_networkd_wait_online }}'

- name: remove systemd-networkd-wait-online.service override
  file:
    path: /etc/systemd/system/systemd-networkd-wait-online.service.d
    state: absent
  notify: reload systemd
  when: not _network_systemd_networkd_wait_online_service_override

- name: deploy wait-for-network-online-then-restart-systemd-networkd.service
  template:
    src: wait-for-network-online-then-restart-systemd-networkd.service.j2
    dest: /etc/systemd/system/wait-for-network-online-then-restart-systemd-networkd.service
    owner: root
    group: root
    mode: '0644'
  when: network_systemd_networkd_wait_for_network_online_then_restart_systemd_networkd_service

- name: enable wait-for-network-online-then-restart-systemd-networkd.service
  systemd:
    name: wait-for-network-online-then-restart-systemd-networkd.service
    enabled: yes
    daemon_reload: yes
  when: network_systemd_networkd_wait_for_network_online_then_restart_systemd_networkd_service

- name: install wireguard tools
  package:
    name: wireguard-tools
  when: network_systemd_install_wireguard_tools
